[platformio]
default_envs = native
src_dir = .

[env]
monitor_speed = 19200

[env:turnout_node]
board = nanoatmega328new
upload_speed = 115200
upload_port = /dev/ttyUSB0
platform = atmelavr
framework = arduino
build_src_filter =
	-<*>
	+<turnout-node/**>

[env:signal_node]
platform = atmelavr
board = nanoatmega328new
upload_speed = 115200
upload_port = /dev/ttyUSB1
framework = arduino
build_src_filter =
	-<*>
	+<signal-node/**>

[env:native]
platform = native
test_build_src = no
