[platformio]
default_envs = turnout_node

[env]
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 19200

[env:turnout_node]
build_src_filter = +<turnout-node/>

[env:signal_node]
build_src_filter = +<signal-node/>
