[platformio]
default_envs = native

[env]
monitor_speed = 19200

[env:turnout_node]
platform = atmelavr
board = nanoatmega328
framework = arduino
build_src_filter = +<turnout-node/>

[env:signal_node]
platform = atmelavr
board = nanoatmega328
framework = arduino
build_src_filter = +<signal-node/>

[env:native]
platform = native
test_build_src = no
